repos:
  - repo: local
    hooks:
    - id: gofmt
      name: gofmt
      entry: sh -c 'gofmt -w .'
      language: system
      require_serial: true

    - id: go-mod-tidy
      name: go mod tidy
      entry: sh -c 'go mod tidy'
      language: system
    
    - id: golangci-lint
      name: golangci lint
      entry: sh -c 'golangci-lint run'
      language: system
      require_serial: true
      